encoding: utf-8

# SEO相关信息
title: Notes
description: 个人笔记
keywords: 
author: 
footerText: ''

baseUrl: 'https://8527.github.io/others'

# 菜单
menu:
  - title: Home
    url: /
  - title: Categories
    url: /pages/categories.html
  - title: Search
    url: /pages/search.html
  - title: About
    url: /pages/about.html

# 文章url前缀，固定格式，不要动
permalink: /posts/:year/:month/:day/:title.html

kramdown:
  auto_ids: true
  input: GFM

exclude: ['CNAME', 'README.md']
